name: SubwaySystem
version: 1.0
main: com.github.pashudzu.SubwaySystemPlugin
api-version: 1.21
author: Pashudzu
description: Subway system plugin

commands:
  subway-system:
    description: "Main command for SubwaySystem"
    usage: "/subway <help|map|station|line>"
    aliases: [metro, subway]
    permission: subway-system.user

permission:
  subway-system.user:
    description: "Basic user permissions for SubwaySystem"
    default: true
  subway-system.upgrade:
    description: "Permission for creating new stations and lines"
    default: false
  subway-system.admin:
    description: "Admin permission for SubwaySystem"
    default: op